name: PR Images Preview

on:
  workflow_run:
    workflows: [ "Generate graphics" ]
    types:
      - completed
    branches-ignore:
      - 'main'


jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v6
      - name: Download PR Artifact
        uses: actions/download-artifact@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          run-id: ${{ github.event.workflow_run.id }}
          name: images
          path: images
      - name: Check for changes
        id: changed
        run: |
          # Compare HEAD with previous commit
          if ! git diff-index --quiet HEAD --; then 
            echo "Changes detected."
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes."
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Push to temporary branch
        if: steps.changed.outputs.files_changed == 'true'
        id: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch pr-images || true
          git checkout pr-images
          git add images/*svg
          git commit -m "Images for #${{ github.event.number }}"
          git push origin -u pr-images
          echo hash=`git rev-parse HEAD` >> $GITHUB_OUTPUT
      - name: Update PR status comment with link
        if: steps.changed.outputs.files_changed == 'true'
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🚀 PR Preview ![generated image](../blob/${{ steps.push.outputs.hash }}/images/spring-quarkus-perf-comparison-latest-throughput-light.svg?raw=true)
          number: ${{ steps.pr.outputs.id }}
      - name: Update PR status comment with absense of link
        if: steps.changed.outputs.files_changed == 'true'
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
           This PR does not change any of the images.
          number: ${{ steps.pr.outputs.id }}